In [1]:
import pandas as pd
import numpy as np
import datetime
import time

In [2]:
# Read data
usd_idr_df = pd.read_csv('bloomberg_usd_idr_2012_2024_processed.csv')

usd_idr_df

,date,open,high,low,close,gap_day,next_close,open_change,high_change,low_change,...,ma_close_5,ma_close_10,prev_open,prev_high,prev_low,prev_close,daily_range,gap_change,close_ma5_ratio,close_ma10_ratio
0,2012-01-02,9150.0,9200.0,9067.0,9080.0,1,9135.0,50.0,-8.0,4.0,...,9074.000000,9070.833333,9100.0,9208.0,9063.0,9067.0,133.0,83.0,1.000661,1.001011
1,2012-01-03,9090.0,9185.0,9090.0,9135.0,1,9137.0,-60.0,-15.0,23.0,...,9094.000000,9080.000000,9150.0,9200.0,9067.0,9080.0,95.0,10.0,1.004508,1.006057
2,2012-01-04,9160.0,9185.0,9137.0,9137.0,1,9193.0,70.0,0.0,47.0,...,9117.333333,9087.125000,9090.0,9185.0,9090.0,9135.0,48.0,25.0,1.002157,1.005489
3,2012-01-05,9175.0,9203.0,9112.0,9193.0,1,9095.0,15.0,18.0,-25.0,...,9136.250000,9104.375000,9160.0,9185.0,9137.0,9137.0,91.0,38.0,1.006212,1.009734
4,2012-01-06,9178.0,9213.0,9095.0,9095.0,3,9150.0,3.0,10.0,-17.0,...,9128.000000,9106.875000,9175.0,9203.0,9112.0,9193.0,118.0,-15.0,0.996385,0.998696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3129,2024-10-21,15463.0,15498.0,15431.0,15495.0,1,15560.0,-60.0,-25.0,-16.0,...,15485.000000,15518.000000,15523.0,15523.0,15447.0,15465.0,67.0,-2.0,1.000646,0.998518
3130,2024-10-22,15534.0,15572.0,15534.0,15560.0,1,15620.0,71.0,74.0,103.0,...,15506.666667,15524.000000,15463.0,15498.0,15431.0,15495.0,38.0,39.0,1.003439,1.002319
3131,2024-10-23,15590.0,15633.0,15590.0,15620.0,1,15584.0,56.0,61.0,56.0,...,15558.333333,15536.000000,15534.0,15572.0,15534.0,15560.0,43.0,30.0,1.003964,1.005407
3132,2024-10-24,15640.0,15644.0,15580.0,15584.0,1,15640.0,50.0,11.0,-10.0,...,15564.750000,15539.000000,15590.0,15633.0,15590.0,15620.0,64.0,20.0,1.001237,1.002896
3133,2024-10-25,15622.0,15643.0,15603.0,15640.0,3,15725.0,-18.0,-1.0,23.0,...,15579.800000,15546.500000,15640.0,15644.0,15580.0,15584.0,40.0,38.0,1.003864,1.006014

In [4]:
# Read data
usd_jpy_df = pd.read_csv('bloomberg_usd_jpy_2012_2024_processed.csv')

usd_jpy_df

,date,open,high,low,close,gap_day,next_close,open_change,high_change,low_change,...,ma_close_5,ma_close_10,prev_open,prev_high,prev_low,prev_close,daily_range,gap_change,close_ma5_ratio,close_ma10_ratio
0,2012-01-02,76.84,77.17,76.33,76.90,1,76.74,-0.80,-0.57,-0.56,...,77.150000,77.541667,77.64,77.74,76.89,76.91,0.84,-0.07,0.996760,0.991725
1,2012-01-03,76.90,76.97,76.63,76.74,1,76.72,0.06,-0.20,0.30,...,76.850000,77.427143,76.84,77.17,76.33,76.90,0.34,0.00,0.998569,0.991125
2,2012-01-04,76.74,76.83,76.61,76.72,1,77.12,-0.16,-0.14,-0.02,...,76.786667,77.338750,76.90,76.97,76.63,76.74,0.22,0.00,0.999132,0.991999
3,2012-01-05,76.72,77.25,76.66,77.12,1,76.97,-0.02,0.42,0.05,...,76.870000,77.231250,76.74,76.83,76.61,76.72,0.59,0.00,1.003252,0.998560
4,2012-01-06,77.12,77.34,76.96,76.97,3,76.86,0.40,0.09,0.30,...,76.890000,77.117500,76.72,77.25,76.66,77.12,0.38,0.00,1.001040,0.998087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3340,2024-10-21,149.56,150.89,149.09,150.84,1,151.08,-0.65,0.61,-0.28,...,150.193333,149.863333,150.21,150.28,149.37,149.53,1.80,0.03,1.004306,1.006517
3341,2024-10-22,150.84,151.20,150.50,151.08,1,152.76,1.28,0.31,1.41,...,150.483333,150.037143,149.56,150.89,149.09,150.84,0.70,0.00,1.003965,1.006951
3342,2024-10-23,151.08,153.19,151.03,152.76,1,151.83,0.24,1.99,0.53,...,151.560000,150.377500,150.84,151.20,150.50,151.08,2.16,0.00,1.007918,1.015843
3343,2024-10-24,152.76,152.83,151.55,151.83,1,152.31,1.68,-0.36,0.52,...,151.627500,150.636250,151.08,153.19,151.03,152.76,1.28,0.00,1.001336,1.007925
3344,2024-10-25,151.83,152.38,151.46,152.31,3,153.29,-0.93,-0.45,-0.09,...,151.764000,151.025000,152.76,152.83,151.55,151.83,0.92,0.00,1.003598,1.008509