In [20]:
import polars as pl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
import time
import json

from datetime import datetime, timedelta

In [21]:
# Read data
df = pd.read_parquet('USDT_IDRT.parquet')

df

,coin,opentime,openprice,highprice,lowprice,closeprice,volume,closetime,quotevolume,trades,taker_buy_volume,taker_buy_quote
0,USDT,1587096000000,15603.0,15603.0,3500.0,3800.0,2111.00,1587096059999,7950998.02,12,180.42,665115.90
1,USDT,1587096060000,3900.0,9999.0,3121.0,9999.0,1518.80,1587096119999,8007685.55,30,569.40,4303589.21
2,USDT,1587096120000,9999.0,15400.0,3121.0,15300.0,3436.21,1587096179999,48425887.45,26,1093.32,15982700.25
3,USDT,1587096180000,15300.0,15399.0,3905.0,13662.0,2006.86,1587096239999,25022275.06,20,21.70,334158.30
4,USDT,1587096240000,13662.0,15000.0,3905.0,15000.0,1858.21,1587096299999,21579335.19,25,473.01,6156983.66
...,...,...,...,...,...,...,...,...,...,...,...,...
2375391,USDT,1729727700000,15691.0,15691.0,15691.0,15691.0,0.00,1729727759999,0.00,0,0.00,0.00
2375392,USDT,1729727760000,15691.0,15691.0,15691.0,15691.0,0.00,1729727819999,0.00,0,0.00,0.00
2375393,USDT,1729727820000,15691.0,15691.0,15691.0,15691.0,5.00,1729727879999,78455.00,1,0.00,0.00
2375394,USDT,1729727880000,15693.0,15693.0,15693.0,15693.0,5.00,1729727939999,78465.00,1,5.00,78465.00
2375395,USDT,1729727940000,15693.0,15693.0,15693.0,15693.0,0.00,1729727999999,0.00,0,0.00,0.00

In [22]:
df.drop(['coin'], axis=1, inplace=True)

df = df[df['opentime'] >= 1679666460000]

df

,opentime,openprice,highprice,lowprice,closeprice,volume,closetime,quotevolume,trades,taker_buy_volume,taker_buy_quote
1541037,1679666460000,15299.0,15299.0,15299.0,15299.0,69.0,1679666519999,1055631.0,1,69.0,1055631.0
1541038,1679666520000,15255.0,15255.0,15248.0,15248.0,120.0,1679666579999,1829830.0,2,0.0,0.0
1541039,1679666580000,15248.0,15248.0,15248.0,15248.0,0.0,1679666639999,0.0,0,0.0,0.0
1541040,1679666640000,15275.0,15275.0,15275.0,15275.0,11.0,1679666699999,168025.0,1,0.0,0.0
1541041,1679666700000,15275.0,15275.0,15275.0,15275.0,10.0,1679666759999,152750.0,1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2375391,1729727700000,15691.0,15691.0,15691.0,15691.0,0.0,1729727759999,0.0,0,0.0,0.0
2375392,1729727760000,15691.0,15691.0,15691.0,15691.0,0.0,1729727819999,0.0,0,0.0,0.0
2375393,1729727820000,15691.0,15691.0,15691.0,15691.0,5.0,1729727879999,78455.0,1,0.0,0.0
2375394,1729727880000,15693.0,15693.0,15693.0,15693.0,5.0,1729727939999,78465.0,1,5.0,78465.0
2375395,1729727940000,15693.0,15693.0,15693.0,15693.0,0.0,1729727999999,0.0,0,0.0,0.0

In [9]:
# timestamp_str = '2023-03-24 14:01:00.000000'

# # Convert to datetime
# timestamp = pd.to_datetime(timestamp_str)

# # Convert to milliseconds since Unix epoch
# milliseconds_since_epoch = int(timestamp.timestamp() * 1000)

# milliseconds_since_epoch

1679666460000

In [ ]:
# 2023-03-24 14:01:00.000000

In [23]:
# Assuming df['opentime'] is the column with timestamps in milliseconds
df['opentime'] = pd.to_datetime(df['opentime'], unit='ms')
df['closetime'] = pd.to_datetime(df['closetime'], unit='ms')

# Format to display in 'YYYY-MM-DD HH:MM:SS.SSS' format
df['opentime'] = df['opentime'].dt.strftime('%Y-%m-%d %H:%M:%S.%f')
df['closetime'] = df['closetime'].dt.strftime('%Y-%m-%d %H:%M:%S.%f')

df

/tmp/ipykernel_861917/2161759317.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['opentime'] = pd.to_datetime(df['opentime'], unit='ms')
/tmp/ipykernel_861917/2161759317.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['closetime'] = pd.to_datetime(df['closetime'], unit='ms')
/tmp/ipykernel_861917/2161759317.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['opentime'] = df['opentime'].dt.strftime('%Y-%m-%d %H:%M:%S.%f')
/tmp/ipykernel_861917/2161759317.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['closetime'] = df['closetime'].dt.strftime('%Y-%m-%d %H:%M:%S.%f')

,opentime,openprice,highprice,lowprice,closeprice,volume,closetime,quotevolume,trades,taker_buy_volume,taker_buy_quote
1541037,2023-03-24 14:01:00.000000,15299.0,15299.0,15299.0,15299.0,69.0,2023-03-24 14:01:59.999000,1055631.0,1,69.0,1055631.0
1541038,2023-03-24 14:02:00.000000,15255.0,15255.0,15248.0,15248.0,120.0,2023-03-24 14:02:59.999000,1829830.0,2,0.0,0.0
1541039,2023-03-24 14:03:00.000000,15248.0,15248.0,15248.0,15248.0,0.0,2023-03-24 14:03:59.999000,0.0,0,0.0,0.0
1541040,2023-03-24 14:04:00.000000,15275.0,15275.0,15275.0,15275.0,11.0,2023-03-24 14:04:59.999000,168025.0,1,0.0,0.0
1541041,2023-03-24 14:05:00.000000,15275.0,15275.0,15275.0,15275.0,10.0,2023-03-24 14:05:59.999000,152750.0,1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2375391,2024-10-23 23:55:00.000000,15691.0,15691.0,15691.0,15691.0,0.0,2024-10-23 23:55:59.999000,0.0,0,0.0,0.0
2375392,2024-10-23 23:56:00.000000,15691.0,15691.0,15691.0,15691.0,0.0,2024-10-23 23:56:59.999000,0.0,0,0.0,0.0
2375393,2024-10-23 23:57:00.000000,15691.0,15691.0,15691.0,15691.0,5.0,2024-10-23 23:57:59.999000,78455.0,1,0.0,0.0
2375394,2024-10-23 23:58:00.000000,15693.0,15693.0,15693.0,15693.0,5.0,2024-10-23 23:58:59.999000,78465.0,1,5.0,78465.0
2375395,2024-10-23 23:59:00.000000,15693.0,15693.0,15693.0,15693.0,0.0,2024-10-23 23:59:59.999000,0.0,0,0.0,0.0

In [19]:
df

shape: (834_359, 22)
┌────────────┬───────────┬───────────┬──────────┬───┬─────────┬────────────┬───────────┬───────────┐
│ opentime   ┆ openprice ┆ highprice ┆ lowprice ┆ … ┆ sma_10  ┆ volume_cha ┆ volume_ra ┆ next_clos │
│ ---        ┆ ---       ┆ ---       ┆ ---      ┆   ┆ ---     ┆ nge        ┆ tio       ┆ eprice    │
│ str        ┆ f64       ┆ f64       ┆ f64      ┆   ┆ f64     ┆ ---        ┆ ---       ┆ ---       │
│            ┆           ┆           ┆          ┆   ┆         ┆ f64        ┆ f64       ┆ f64       │
╞════════════╪═══════════╪═══════════╪══════════╪═══╪═════════╪════════════╪═══════════╪═══════════╡
│ 2023-03-24 ┆ 15299.0   ┆ 15299.0   ┆ 15299.0  ┆ … ┆ null    ┆ null       ┆ inf       ┆ 15248.0   │
│ 14:01:00.0 ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 00000      ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 2023-03-24 ┆ 15255.0   ┆ 15255.0   ┆ 15248.0  ┆ … ┆ null    ┆ 51.0       ┆ 0.0       ┆ 15248.0   │
│ 14:02:00.0 ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 00000      ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 2023-03-24 ┆ 15248.0   ┆ 15248.0   ┆ 15248.0  ┆ … ┆ null    ┆ -120.0     ┆ NaN       ┆ 15275.0   │
│ 14:03:00.0 ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 00000      ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 2023-03-24 ┆ 15275.0   ┆ 15275.0   ┆ 15275.0  ┆ … ┆ null    ┆ 11.0       ┆ 0.0       ┆ 15275.0   │
│ 14:04:00.0 ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 00000      ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 2023-03-24 ┆ 15275.0   ┆ 15275.0   ┆ 15275.0  ┆ … ┆ null    ┆ -1.0       ┆ 0.0       ┆ 15315.0   │
│ 14:05:00.0 ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 00000      ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …        ┆ … ┆ …       ┆ …          ┆ …         ┆ …         │
│ 2024-10-23 ┆ 15691.0   ┆ 15691.0   ┆ 15691.0  ┆ … ┆ 15691.0 ┆ 0.0        ┆ NaN       ┆ 15691.0   │
│ 23:55:00.0 ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 00000      ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 2024-10-23 ┆ 15691.0   ┆ 15691.0   ┆ 15691.0  ┆ … ┆ 15691.0 ┆ 0.0        ┆ NaN       ┆ 15691.0   │
│ 23:56:00.0 ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 00000      ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 2024-10-23 ┆ 15691.0   ┆ 15691.0   ┆ 15691.0  ┆ … ┆ 15691.0 ┆ 5.0        ┆ 0.0       ┆ 15693.0   │
│ 23:57:00.0 ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 00000      ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 2024-10-23 ┆ 15693.0   ┆ 15693.0   ┆ 15693.0  ┆ … ┆ 15691.2 ┆ 0.0        ┆ inf       ┆ 15693.0   │
│ 23:58:00.0 ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 00000      ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 2024-10-23 ┆ 15693.0   ┆ 15693.0   ┆ 15693.0  ┆ … ┆ 15691.4 ┆ -5.0       ┆ NaN       ┆ null      │
│ 23:59:00.0 ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
│ 00000      ┆           ┆           ┆          ┆   ┆         ┆            ┆           ┆           │
└────────────┴───────────┴───────────┴──────────┴───┴─────────┴────────────┴───────────┴───────────┘

In [26]:
# Change the df to polars if its in pandas
if isinstance(df, pd.DataFrame):
    # Convert pandas DataFrame to polars DataFrame
    df = pl.from_pandas(df)

# Features engineering
df = df.with_columns([
    # Maker Buy
    (pl.col("volume") - pl.col("taker_buy_volume")).alias("maker_buy_volume"),
    (pl.col("quotevolume") - pl.col("taker_buy_quote")).alias("maker_buy_quote_volume"),

    # Price Deltas
    (pl.col("closeprice") - pl.col("openprice")).alias("open_close_delta"),
    (pl.col("highprice") - pl.col("lowprice")).alias("low_high_delta"),
    (pl.col("highprice") - pl.col("openprice")).alias("high_open_delta"),
    (pl.col("closeprice") / pl.col("openprice") - 1).alias("close_open_ratio"),
    
    # Moving Averages
    pl.col("closeprice").rolling_mean(window_size=5).alias("sma_5"),
    pl.col("closeprice").rolling_mean(window_size=10).alias("sma_10"),
    
    # Changes from lag_1
    (pl.col("volume") - pl.col("volume").shift(1)).alias("volume_change"),
    
    # Taker vs Maker Volume Ratio
    (pl.col("taker_buy_volume") / (pl.col("volume") - pl.col("taker_buy_volume"))).alias("volume_ratio"),
    
    # Lagged Features (next close and volume)
    pl.col("closeprice").shift(-1).alias("next_closeprice"),  # Next close price


])


# Function to replace NaN and infinite values in specified columns
def replace_nan_inf(df: pl.DataFrame, col_names: list, replacement: float = 0) -> pl.DataFrame:
    for col in col_names:
        df = df.with_columns(
            pl.when(pl.col(col).is_nan() | pl.col(col).is_in([np.inf, -np.inf]))
            .then(replacement)
            .otherwise(pl.col(col)).alias(col)
        )
    return df

# List of columns to replace NaN and infinite values with 0
columns_to_replace = [
    "volume_ratio", "maker_buy_volume", "maker_buy_quote_volume",
    "open_close_delta", "low_high_delta", "high_open_delta",
    "close_open_ratio", "sma_5", "sma_10", "volume_change",
    "next_closeprice"
]

# Replace NaN and infinite values with 0 using the utility function
df = replace_nan_inf(df, columns_to_replace)

# Calculate change from previous lag for specified columns
columns_to_change = [
    'opentime','openprice', 'highprice', 'lowprice', 'closeprice', 'closetime', 'volume', 
    'quotevolume', 'trades', 'taker_buy_volume', 'taker_buy_quote', 
    'maker_buy_volume', 'maker_buy_quote_volume', 'open_close_delta', 
    'low_high_delta', 'high_open_delta', 'close_open_ratio', 
    'sma_5', 'sma_10', 'volume_change', 'volume_ratio', 
    'next_closeprice'
]

# Convert necessary columns to numeric types if they are not already
numeric_columns = ['openprice', 'highprice', 'lowprice', 'closeprice', 
                   'volume', 'quotevolume', 'trades', 
                   'taker_buy_volume', 'taker_buy_quote']

# Use pl.col().cast() to convert columns to floats
for col in numeric_columns:
    df = df.with_columns(pl.col(col).cast(pl.Float64).alias(col))

# Calculate change from previous lag for specified columns
columns_to_change = [
    'opentime', 'openprice', 'highprice', 'lowprice', 'closeprice', 
    'closetime', 'volume', 'quotevolume', 'trades', 'taker_buy_volume', 
    'taker_buy_quote', 'maker_buy_volume', 'maker_buy_quote_volume', 
    'open_close_delta', 'low_high_delta', 'high_open_delta', 
    'close_open_ratio', 'sma_5', 'sma_10', 'volume_change', 
    'volume_ratio', 'next_closeprice'
]

# Calculate the change and create new columns
for col in columns_to_change:
    change_col_name = f"{col}_change"
    
    # Only calculate change for numeric columns
    if col in numeric_columns:
        df = df.with_columns(
            (pl.col(col) - pl.col(col).shift(1)).alias(change_col_name)  # Calculate the change
        )

# Display the updated DataFrame
df

shape: (834_359, 30)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ opentime  ┆ openprice ┆ highprice ┆ lowprice ┆ … ┆ quotevolu ┆ trades_ch ┆ taker_buy ┆ taker_buy │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ me_change ┆ ange      ┆ _volume_c ┆ _quote_ch │
│ str       ┆ f64       ┆ f64       ┆ f64      ┆   ┆ ---       ┆ ---       ┆ hange     ┆ ange      │
│           ┆           ┆           ┆          ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2023-03-2 ┆ 15299.0   ┆ 15299.0   ┆ 15299.0  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 4 14:01:0 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0.000000  ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2023-03-2 ┆ 15255.0   ┆ 15255.0   ┆ 15248.0  ┆ … ┆ 774199.0  ┆ 1.0       ┆ -69.0     ┆ -1.055631 │
│ 4 14:02:0 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ e6        │
│ 0.000000  ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2023-03-2 ┆ 15248.0   ┆ 15248.0   ┆ 15248.0  ┆ … ┆ -1.82983e ┆ -2.0      ┆ 0.0       ┆ 0.0       │
│ 4 14:03:0 ┆           ┆           ┆          ┆   ┆ 6         ┆           ┆           ┆           │
│ 0.000000  ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2023-03-2 ┆ 15275.0   ┆ 15275.0   ┆ 15275.0  ┆ … ┆ 168025.0  ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│ 4 14:04:0 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0.000000  ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2023-03-2 ┆ 15275.0   ┆ 15275.0   ┆ 15275.0  ┆ … ┆ -15275.0  ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 4 14:05:0 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0.000000  ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024-10-2 ┆ 15691.0   ┆ 15691.0   ┆ 15691.0  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 3 23:55:0 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0.000000  ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2024-10-2 ┆ 15691.0   ┆ 15691.0   ┆ 15691.0  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 3 23:56:0 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0.000000  ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2024-10-2 ┆ 15691.0   ┆ 15691.0   ┆ 15691.0  ┆ … ┆ 78455.0   ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│ 3 23:57:0 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0.000000  ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2024-10-2 ┆ 15693.0   ┆ 15693.0   ┆ 15693.0  ┆ … ┆ 10.0      ┆ 0.0       ┆ 5.0       ┆ 78465.0   │
│ 3 23:58:0 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0.000000  ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2024-10-2 ┆ 15693.0   ┆ 15693.0   ┆ 15693.0  ┆ … ┆ -78465.0  ┆ -1.0      ┆ -5.0      ┆ -78465.0  │
│ 3 23:59:0 ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 0.000000  ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘